spring:
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localnetwork:3306/cast?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: community
      password: 1234
      connection-test-query: SELECT NOW() FROM dual
  data:
    redis:
      host: localnetwork
      port: 6379
  session:
    redis:
      flush-mode: on-save
      namespace: spring:session
    timeout: 30m

server:
  port: 8181
